# .github/workflows/build.yml
name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            output_name: ITU-CRN-Monitor.exe
          - os: macos-latest
            output_name: ITU-CRN-Monitor-mac
          - os: ubuntu-latest
            output_name: ITU-CRN-Monitor-linux

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests
        
    - name: Build executable (Windows/Linux)
      if: runner.os != 'macOS'
      run: |
        pyinstaller --onefile --windowed --name ITU-CRN-Monitor crn_monitor_gui.py
        
    - name: Build executable (macOS)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --name ITU-CRN-Monitor crn_monitor_gui.py
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: |
          dist/ITU-CRN-Monitor*