name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            output_name: ITU-CRN-Monitor.exe
          - os: macos-13 # Use an older macOS runner for better compatibility
            output_name: ITU-CRN-Monitor-mac
          - os: ubuntu-latest
            output_name: ITU-CRN-Monitor-linux

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Tkinter dependency for Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y python3-tk
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests

    - name: Build executable with PyInstaller
      run: pyinstaller --onefile --windowed --name ITU-CRN-Monitor crn_taker_gui.py

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: dist/ITU-CRN-Monitor*